CREATE TABLE IF NOT EXISTS assessment_runtime_settings (
    setting_key Utf8 NOT NULL,
    setting_value Utf8 NOT NULL,
    updated_at Timestamp NOT NULL,
    PRIMARY KEY (setting_key)
);

CREATE TABLE IF NOT EXISTS assessment_banks (
    test_id Utf8 NOT NULL,
    bank_version Utf8 NOT NULL,
    object_key Utf8 NOT NULL,
    private_digest Utf8 NOT NULL,
    public_digest Utf8 NOT NULL,
    active Bool NOT NULL,
    updated_at Timestamp NOT NULL,
    PRIMARY KEY (test_id, bank_version)
);

CREATE TABLE IF NOT EXISTS assessment_invites (
    invite_id Utf8 NOT NULL,
    request_id Utf8 NOT NULL,
    test_id Utf8 NOT NULL,
    code_hash Utf8 NOT NULL,
    identity_hash Utf8 NOT NULL,
    email_masked Utf8 NOT NULL,
    purpose Utf8 NOT NULL,
    allow_retake Bool NOT NULL,
    valid_for_hours Int32,
    state Utf8 NOT NULL,
    issued_at Timestamp NOT NULL,
    expires_at Timestamp NOT NULL,
    activated_at Timestamp,
    completed_at Timestamp,
    revoked_at Timestamp,
    revoke_request_id Utf8,
    attempt_id Utf8,
    purge_at Timestamp NOT NULL,
    PRIMARY KEY (invite_id),
    INDEX invite_request GLOBAL ON (request_id),
    INDEX invite_code GLOBAL ON (code_hash),
    INDEX invite_test_identity GLOBAL ON (test_id, identity_hash)
) WITH (TTL = Interval("PT0S") ON purge_at);

CREATE TABLE IF NOT EXISTS assessment_sessions (
    attempt_id Utf8 NOT NULL,
    invite_id Utf8 NOT NULL,
    begin_request_id Utf8 NOT NULL,
    state Utf8 NOT NULL,
    test_id Utf8 NOT NULL,
    test_version Utf8 NOT NULL,
    bank_version Utf8 NOT NULL,
    public_digest Utf8 NOT NULL,
    question_ids JsonDocument NOT NULL,
    question_set_hash Utf8 NOT NULL,
    identity_hash Utf8 NOT NULL,
    fingerprint_hash Utf8 NOT NULL,
    token_jti Utf8 NOT NULL,
    token_issued_at Timestamp NOT NULL,
    token_expires_at Timestamp NOT NULL,
    started_at Timestamp NOT NULL,
    privacy_consent_version Utf8 NOT NULL,
    privacy_consented_at Timestamp NOT NULL,
    age_confirmed Bool NOT NULL,
    save_request_id Utf8,
    submission_hash Utf8,
    reserved_at Timestamp,
    result_code Utf8,
    result_json JsonDocument,
    completed_at Timestamp,
    purge_at Timestamp NOT NULL,
    PRIMARY KEY (invite_id),
    INDEX session_attempt GLOBAL ON (attempt_id),
    INDEX session_identity GLOBAL ON (test_id, identity_hash),
    INDEX session_result_code GLOBAL ON (result_code)
) WITH (TTL = Interval("PT0S") ON purge_at);

CREATE TABLE IF NOT EXISTS assessment_results (
    result_code Utf8 NOT NULL,
    request_id Utf8 NOT NULL,
    attempt_id Utf8 NOT NULL,
    test_id Utf8 NOT NULL,
    test_title Utf8 NOT NULL,
    bank_version Utf8 NOT NULL,
    candidate_name Utf8 NOT NULL,
    candidate_email Utf8 NOT NULL,
    candidate_telegram Utf8 NOT NULL,
    english_level Utf8 NOT NULL,
    candidate_source Utf8 NOT NULL,
    candidate_experience Utf8 NOT NULL,
    raw_score Double NOT NULL,
    raw_total Double NOT NULL,
    final_score Double NOT NULL,
    percent Double NOT NULL,
    unanswered_count Int32 NOT NULL,
    tab_switches Int32 NOT NULL,
    advisory_penalty Int32 NOT NULL,
    trust_score Double NOT NULL,
    result_status Utf8 NOT NULL,
    badge Utf8 NOT NULL,
    recommendation Utf8 NOT NULL,
    block_results JsonDocument NOT NULL,
    answer_details JsonDocument NOT NULL,
    score_verification Utf8 NOT NULL,
    scoring_algorithm_version Utf8 NOT NULL,
    telemetry_verification Utf8 NOT NULL,
    privacy_consent_version Utf8 NOT NULL,
    privacy_consented_at Timestamp NOT NULL,
    age_confirmed Bool NOT NULL,
    report_created Bool NOT NULL,
    report_object_key Utf8,
    submission_hash Utf8 NOT NULL,
    completed_at Timestamp NOT NULL,
    technical Bool NOT NULL,
    purge_at Timestamp NOT NULL,
    PRIMARY KEY (result_code),
    INDEX result_request GLOBAL ON (request_id),
    INDEX result_attempt GLOBAL ON (attempt_id),
    INDEX result_test_completed GLOBAL ON (test_id, completed_at)
) WITH (TTL = Interval("PT0S") ON purge_at);

CREATE TABLE IF NOT EXISTS assessment_audit_events (
    event_date Date NOT NULL,
    event_id Utf8 NOT NULL,
    event_type Utf8 NOT NULL,
    subject_hash Utf8 NOT NULL,
    outcome Utf8 NOT NULL,
    created_at Timestamp NOT NULL,
    purge_at Timestamp NOT NULL,
    PRIMARY KEY (event_date, event_id)
) WITH (TTL = Interval("PT0S") ON purge_at);
